Repository openfheorg/openfhe-python, pull requests merged in 2023-11, with the labels that each got.

#76 EvalAdd Fix
  src/include/docstrings/cryptocontext_docs.h
  src/lib/bindings.cpp
Labels: new feature

#78 updated to v0.8.2
  CMakeLists.txt
  README.md
Labels: documentation

#77 EvalAdd Fix + Documentation updates
  CMakeLists.txt
  README.md
  src/include/docstrings/binfhecontext_docs.h
  src/include/docstrings/cryptocontext_docs.h
  src/lib/bindings.cpp
Labels: documentation, new feature
