Repository openfheorg/openfhe-python, pull requests merged in 2024-03, with the labels that each got.

#115 restricted to v1.1.2 of OpenFHE (#114)
  CMakeLists.txt
  README.md
Labels: bug

#116 Fix for v1.1.3/4
  CMakeLists.txt
  examples/pke/scheme-switching.py
  src/include/bindings.h
  src/include/docstrings/cryptocontext_docs.h
  src/include/pke/cryptocontext_wrapper.h
  src/lib/bindings.cpp
  src/lib/binfhe_bindings.cpp
  src/lib/pke/cryptocontext_wrapper.cpp
Labels: bug

#118 Updates to 0.8.6
  CMakeLists.txt
  README.md
Labels: new release

#119 Updates to v0.8.6
  CMakeLists.txt
  README.md
  examples/pke/scheme-switching.py
  src/include/bindings.h
  src/include/docstrings/cryptocontext_docs.h
  src/include/pke/cryptocontext_wrapper.h
  src/lib/bindings.cpp
  src/lib/binfhe_bindings.cpp
  src/lib/pke/cryptocontext_wrapper.cpp
Labels: new release

#121 Updates main using dev (macOS fix)
  CMakeLists.txt
Labels: bug

#111 Adolgert unit test dir
  setup.py
  tests/README.md
  tests/conftest.py
  tests/test_bgv.py
  tests/test_ckks.py
  tests/test_cryptocontext.py
  tests/test_serial_cc.py
Labels: new feature, automation

#123 Added workflows/manual.yml (dev)
  .github/workflows/manual.yml
Labels: new feature, automation

#124 Added workflows/manual.yml (main)
  .github/workflows/manual.yml
Labels: new feature, automation
