Repository openfheorg/openfhe-python, pull requests merged in 2025-07, with the labels that each got.

#231 Sync'ed API bindings with openfhe-development
  src/lib/bindings.cpp
Labels: new feature

#232 Lowered the value of scalingModSize in advanced-real-numbers-128.py
  examples/pke/advanced-real-numbers-128.py
Labels: bug

#233 Updates for the new openfhe version
  CMakeLists.txt
  README.md
Labels: new release

#234 Updates to v1.3.1.0
  CMakeLists.txt
  README.md
  __init__.py
  docs/Makefile
  examples/pke/advanced-real-numbers-128.py
  examples/pke/interactive-bootstrapping.py
  openfhe/__init__.py
  setup.py
  src/include/pke/cryptocontext_wrapper.h
  src/lib/bindings.cpp
  src/lib/pke/cryptocontext_wrapper.cpp
Labels: new release

#236 Updated the cmake version
  CMakeLists.txt
Labels: new feature
